name: Deploy to Amazon ECS

on:
  push:
    branches:
      - '*'

env:
  AWS_REGION: us-east-1                   # set this to your preferred AWS region, e.g. us-west-1
  EC2_INSTANCE_IP: 3.91.201.73        # set this to the public IP or DNS of your EC2 instance
  EC2_INSTANCE_USER: ec2-user             # set this to the username for connecting to your EC2 instance          
  CONTAINER_NAME: malaria-app
  DOCKER_HUB_REPOSITORY: kl3374/malaria-stats

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.x

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        cd backend
        pip install -r requirements.txt

    - name: Run Unit Tests
      run:
        python3 -m unittest backend/tests/test_app.py

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        push: true
        dockerfile: ./Dockerfile
        tags: ${{ env.DOCKER_HUB_REPOSITORY }}:latest

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.EC2_INSTANCE_IP }} 
        username: ${{ env.EC2_INSTANCE_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          cd /home/ec2-user/backend
          docker rm -v -f $(docker ps -qa)
          docker pull ${{ env.DOCKER_HUB_REPOSITORY }}:latest
          docker run -d --name ${{ env.CONTAINER_NAME }} -p 7071:7071 ${{ env.DOCKER_HUB_REPOSITORY }}:latest
          
